### ISSUE TITLE
Music Status does not update

### ISSUE THREAD

**Issue by ghost** [DiNitride/Discord-Music-Status#10]
It's not a local issue, friends in the discord channel and even on a separate account logged into my phone, I cannot see the music status displayed.

It works fine in the command line, it states what song is playing and also Split is working correctly and displaying what song is playing. What can we do?

**Comment by Tommysonic5** [comment]
I'm having the same issue as of about a week ago. It used to work but doesn't anymore.

**Comment by DiNitride** [comment]
Update Discord.py, there was a change to the Discord API

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Easy, that fixed it.

Maybe add into the project information that the command to update the Discord API is "pip install discord.py --update"

**Comment by DiNitride** [comment]
Sure
