### ISSUE TITLE
py.exe isn't displaying nor Kana/Kanji nor Hangeul.

### ISSUE THREAD

**Issue by xSnow74** [DiNitride/Discord-Music-Status#12]
Hi,
I tried to play some asian music on Spotify but although titles are correctly fetched by Snip, py.exe appears to be unable to display them correctly

how py.exe wrote them > https://puu.sh/xlGp7/cba25cc26a.png

how they're displayed on snip.txt >
https://puu.sh/xlGsn/6b5a017c19.png
https://puu.sh/xlGtK/a438f7329e.png

Is there any way to fix that ?

Thanks in advance (and apologize if my english is somehow broken).

**Comment by xSnow74** [comment]
Well, should've asked before writing the issue, but seems they're correctly displayed on Discord, that was a bit confusing, case closed i guess.

**Comment by DiNitride** [comment]
Sick

**Comment by miawgogo** [comment]
Just noting this as I noticed this with my mpris fork, the reason this doesn't show up in the terminal is that the encoding had been forced to use ASCII instead of UTF-8(Unicode), the default encoding in python 3
