### ISSUE TITLE
I get this error message

### ISSUE THREAD

**Issue by miguelogin** [DiNitride/Discord-Music-Status#16]
http://prntscr.com/gnnoua

**Comment by DiNitride** [comment]
What version of Python are you running

**Comment by miguelogin** [comment]
3.5

**Comment by DiNitride** [comment]
Did you read the requirements?

**Comment by DiNitride** [comment]
https://github.com/DiNitride/Discord-Music-Status/blob/master/README.md#requirements

**Comment by miguelogin** [comment]
Oh, i didn't noticed. Sorry

**Comment by DiNitride** [comment]
No worries, I make use of f-strings which is Python 3.6 > only. You'll have to update your install or use a virtualenv
