### ISSUE TITLE
Discord status not changing

### ISSUE THREAD

**Issue by shweegl** [DiNitride/Discord-Music-Status#17]
Hello, my discord status is not changing although it says this in my cmd: 
![image](https://user-images.githubusercontent.com/27150301/30669055-27cc26a6-9e5d-11e7-87e2-a09d0274311e.png)

If i wanna set the status manually under "games" tab in settings, I see a song name but it doesn't change if i change a song. Please help me, really love the idea! :D

**Comment by DiNitride** [comment]
You do not set it manually under the games tab.

Please refer to the README.md, this **does not show up for you**. However your friends and anyone *else* on Discord **will be able to**. I cannot make it show up for your client

**Comment by shweegl** [comment]
oh i'm sorry. It does work as intended then, thank you so much! 👍

**Comment by DiNitride** [comment]
No problem
