### ISSUE TITLE
Won't launch.

### ISSUE THREAD

**Issue by EvilWalks** [DiNitride/Discord-Music-Status#19]
I have set up python and everything correctly, I believe. When I try to run run.py for the first time to generate a config file, it just flashes up a terminal too quick to read anything, and closes, with no config file generated. 

Anyone able to shed some light on what I may have done wrong? 

I'm on Windows 10 for what it's worth.

**Comment by DiNitride** [comment]
Have you installed Discord.py and Logbook?

**Comment by EvilWalks** [comment]
Yes, I do. I have managed to confirm that. It may just be I'm simply not familiar with command line stuff to get this going unfortunately. I was using a different script that you just edited the config file and ran it, but it's no longer working. Might have to do some study before I try this again.

**Comment by DiNitride** [comment]
you should just be able to run the Python file. If it is closing randomly then it is likely to be a python error.

What version of Python are you using?
and is it generating a last-run.log

**Comment by EvilWalks** [comment]
Python35. No last-run.log. 

Double clicking to launch the run.py gives the same issue. A terminal pops up but closes just as fast as it opened.

**Comment by DiNitride** [comment]
Please refer to the requirements for this program.

**Comment by DiNitride** [comment]
Please refer to the requirements for this program.

**Comment by EvilWalks** [comment]
Apologies, 3.6 in the requirements is what I have installed. I also have 2.7 installed. Should I just have the one installed?

**Comment by DiNitride** [comment]
You need to make sure you are running it with the 3.6 interpreter, not the 2.7

**Comment by EvilWalks** [comment]
I removed all other versions of Python, rebooted, installed 3.6.2 again, rebooted, and still the same problem. Just going to give up on having now playing displayed. Cheers for the help mate. :)

**Comment by EvilWalks** [comment]
Scratch all of the above. I now have a config file generated. Thanks a bunch mate... I'm not sure how I've fixed it, but you've got me on to the path that has done it. :)

When checking from another discord account, doesn't seem to be displaying, but that's probably a Discord issue I guess, since it appears to be running fine (isn't giving any errors)

**Comment by DiNitride** [comment]
It should be displaying on another account, is it saying that it is updating the status in the log?
