### ISSUE TITLE
Spotify from other music player

### ISSUE THREAD

**Issue by ferdianexe** [DiNitride/Discord-Music-Status#21]
hey what a great bot you have...
but is that true if the application song such spotify played some music there are imported from my file , it wont change the discord status ?

thanks !
by the way the imported playlist were from music media player

**Comment by DiNitride** [comment]
Uh, I'm not entirely sure what you mean? Do you mean it doesn't update your status if you play local files on Spotify?

**Comment by ferdianexe** [comment]
Ah sorry....
first i already conclude that the program gonna update my status if and only if the song that i played in the local files are the song that recognize in spotify itself
that means the system cannot change its status if the song in our local files isnt in the spotify itself
great applications ! nice
