### ISSUE TITLE
Not logging in?

### ISSUE THREAD

**Issue by X-Vaskys** [DiNitride/Discord-Music-Status#22]
Bot is taking loads of time to log-in.

**Comment by DiNitride** [comment]
so it is logging in...?

user accounts can sometimes take a while to log in, you're giving me no details here. if you want your issue solved give me more to work with.

Your title says not logging in then you say it's taking ages, you don't specify how long 'ages' is. You haven't pasted your log either.

**Comment by X-Vaskys** [comment]
It's just stuck on "Logging in" for minutes with no error message, here's the log.  
[https://i.imgur.com/kisv3gN.png](url)

**Comment by DiNitride** [comment]
Is your network connection stable?

**Comment by X-Vaskys** [comment]
As far as I can tell, yes

**Comment by DiNitride** [comment]
sorry, have been busy with college. I have no idea what could be causing this for you other than an unstable or slow network.
