### ISSUE TITLE
Issue with launching.

### ISSUE THREAD

**Issue by 19OliverD** [DiNitride/Discord-Music-Status#23]
pip installed all the dependencies, but when I launch I get this: https://i.imgur.com/PSEOZ8S.png

**Comment by DiNitride** [comment]
What is your snip path pointing to

**Comment by 19OliverD** [comment]
snip = C:\Users\Oliver\Desktop\Snip\Snip.exe

**Comment by 19OliverD** [comment]
Oh, my bad. I'm pointing it to the exe, not the txt. Thanks!
