### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by d1nocan** [DiNitride/Discord-Music-Status#26]
Requirements is correctly loaded.I don't know what the problem is. Can you help me ?

Screenshot: https://i.imgur.com/dA0VYzO.png

**Comment by DiNitride** [comment]
I have no idea, something with your asyncio seems to be broken.
What version of Python are you on?

**Comment by d1nocan** [comment]
Python 3.6.3

**Comment by d1nocan** [comment]
I fixed. It's only working with Python 3.6.0
