### ISSUE TITLE
MusicBee Support

### ISSUE THREAD

**Issue by Ancyker** [DiNitride/Discord-Music-Status#34]
It'd be nice to have MusicBee support, it's pretty popular.

**Comment by DiNitride** [comment]
Request this addition into Snip, the software used to retrieve the current
song - I do not maintain this system nor do I wish to build my own.

**Comment by Phosphorus-M** [comment]
I use this [plugin](https://getmusicbee.com/forum/index.php?topic=9389.0).
With it plugin you can generate external files in format txt.

**Comment by DiNitride** [comment]
That's an external tool, feel free to get it output to the correct text file name for this program, but I am not distributing this with my code.
