### ISSUE TITLE
No config file generated after running run.py?

### ISSUE THREAD

**Issue by aiiman** [DiNitride/Discord-Music-Status#35]
I'm a newbie here. Discord.py and Logbook are installed via pip.

I don't know how to "run" the file, so I tried `cd run.py folder location` and `python run.py` and it shows this 

> File "run.py", line 68
    logger.info(f"Logged in as {bot.user.name} with ID {bot.user.id}")
                                                                    ^
SyntaxError: invalid syntax

I also tried double clicking the file. It just immediately closes after that.

Sorry for this stupid question. ._.

**Comment by aiiman** [comment]
It works now. I had to comment out these from the `run.py` file:

**Line 68**
`logger.info(f"Logged in as {bot.user.name} with ID {bot.user.id}")`

**Line 97**
`logger.info(f"Set Discord status to {song.encode('ascii', 'ignore').decode()}")`

**Comment by DiNitride** [comment]
The required version of Python is 3.6, you are not running 3.6 as f strings
are coming up as invalid syntax which they wouldn't on the 3.6 interpreter

**Comment by aiiman** [comment]
Oh I didn't know that. The installer installed a 32 bit version which is 3.6 and a 64 bit version which is 3.5. I used the 32 bit one and it works perfectly now. But, Snip is having issues with iTunes though. Thank you so much anyways!
