### ISSUE TITLE
not sure if i have everything correct

### ISSUE THREAD

**Issue by needjoystick** [DiNitride/Discord-Music-Status#38]
not sure if i have everything correct, i'm not getting a error that i'm aware i think i put the token/paths in correctly. i'll show you where i placed token/snip path. https://i.imgur.com/Uzt89oq.png https://i.imgur.com/ss8e2MZ.png i'm not really familiar with any of this, but i did manage to intall the logbook and discord.py

**Comment by DiNitride** [comment]
You need to update the config file, not the source code. Please read the instructions. Furthermore, you just revealed your login token, so anyone can log into your account, please delete the screenshots.

**Comment by needjoystick** [comment]
i open the run.py file if that's what you mean by "run" and a screen quickly pops up and disappears, i'm not sure where the config file is. could you tell me where/ how to edit it? sorry for the hassle lol.

**Comment by DiNitride** [comment]
I wrote install instructions. Read them, and it will explain that it creates a config file when you run it the first time. The file should be created in the same directory as the python file. You will also need to revert the file back to the original, as the changes you have made are invalid Python and will cause the script to crash.

https://github.com/DiNitride/Discord-Music-Status/blob/master/README.md#install

**Comment by needjoystick** [comment]
found the config and changed run.py back to previous state, this is what i get now.

[2017-12-25 19:08:47.720762] DEBUG: Discord Music: Loading config files
[2017-12-25 19:08:47.722263] INFO: Discord Music: Config loaded
[2017-12-25 19:08:47.723768] INFO: Discord Music: Logging in
[2017-12-25 19:08:50.490018] INFO: Discord Music: Logged in as Shane|Paralyzed with ID (wasnt sure if i should send this ID)
[2017-12-25 19:08:50.490499] INFO: Discord Music: Ready to start
Task exception was never retrieved
future: <Task finished coro=<music_loop() done, defined at C:\Users\Paralyzed\Downloads\Discord-Music-Status-master\run.py:80> exception=PermissionError(13, 'Permission denied')>
Traceback (most recent call last):
  File "C:\Users\Paralyzed\Downloads\Discord-Music-Status-master\run.py", line 85, in music_loop
    song = pull_song()
  File "C:\Users\Paralyzed\Downloads\Discord-Music-Status-master\run.py", line 102, in pull_song
    with open(snip, encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Paralyzed\\Desktop\\Snip

**Comment by needjoystick** [comment]
never mind i got it!
