### ISSUE TITLE
Functions but doesn't change actual "playing" status

### ISSUE THREAD

**Issue by Swearinbag** [DiNitride/Discord-Music-Status#39]
Installed - followed a few tutorials as I'm new to python and the workings and got them to work but the only Issue now is that my status in Discord doesn't change.

https://i.imgur.com/DQRVge3.png

Any idea what might cause this?

- - -
UPDATE:

Forgot to mention that "display currently running game as a status message" is enabled.

**Comment by DiNitride** [comment]
https://github.com/DiNitride/Discord-Music-Status/blob/master/README.md#the-status-will-not-show-up-for-you-as-discord-does-not-display-it-on-your-own-client-when-you-edit-it-i-cannot-fix-this-your-friends-will-be-able-to-see-it-however-or-you-can-log-into-another-account-and-check

If it still cannot be seen from another account, open another issue
