### ISSUE TITLE
Status doesn't update

### ISSUE THREAD

**Issue by CuteLuciii** [DiNitride/Discord-Music-Status#4]
Hey there, i really like your programm (or what ever those things are called :D) But i have a problem,

i installed and run all the stuff, edited everything as it has to be. And in Discord under playing status i can choose the current song. So far so good. But my problem is, it doesn't update the status. It always stucks on the Song which was played when i added the "game" to my status.

What am i doing wrong?

**Comment by DiNitride** [comment]
Okay first of all, the message will not show up on your client. You do not need to select anything inside Discord. If you have Snip running, and have the variables configured correctly inside the file, once you run the program, it will sign into your Discord account, and modify your game via the API. *This does not appear for you, only others*. You will need to get a friend to check for you

**Comment by CuteLuciii** [comment]
I'm not even really sure if this discord.py was installed correctly. I'm a total noob to python or any other coding. Is it normal that there just pops a window within a millisecond and disappears again? and can i look it up somewhere if it was installed corectly or not?

**Comment by DiNitride** [comment]
No, that is not correct, it should open and stay open, log in, and then display information on which song it is displaying. Something is not configured correctly

**Comment by CuteLuciii** [comment]
I just realized if i try to open your script via CMD there is an error code:

line 37
async_def on_ready():
^
SyntaxError: invalid syntax

Is this any useful for you?

**Comment by DiNitride** [comment]
What version of Python do you have installed?
