### ISSUE TITLE
Import Discord in Line 7 won't work

### ISSUE THREAD

**Issue by fayaine** [DiNitride/Discord-Music-Status#44]
Hey there i got Python and Logbook installed unfortunatly it wont run due to Line 7 where it imports discord. And yes ofc i have discord installed as usual. 

  File "C:\Users\Fay\Desktop\Discord-Music-Status-master\Discord-Music-Status-master\run.py", line 8, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

Any fix ?

Thanks : )

**Comment by DiNitride** [comment]
You haven't installed the Discord library.

Installing Discord =/= The Python Discord library.

You need to install discord.py

**Comment by fayaine** [comment]
Oh gotcha also the newest Snip doesnt work with the current Itunes it just gives an error unfortunately
Would that also work with a different snipper that puts out a .txt with the songname ?

**Comment by DiNitride** [comment]
I can't do anything about that unfortunately, so I'd head over to the snip repo and make an issue if you can, but yes, if you have any other program that can output your song to a text file, simply exchange `snip.txt` for that file in config and it will read from it

**Comment by fayaine** [comment]
Got it working with my snipper : ) only a shame you cant see the status yourself but well :3 
Hopefully thats fixable someday : )

**Comment by glowsticks** [comment]
You could always make a throwaway "test account" to see if it is working.

**Comment by fayaine** [comment]
Yea its working for others i confirmed it just would be great to see it yourself too as games if you play them

**Comment by DiNitride** [comment]
Yeah, it's really annoying but a limitation of Discord we can't get around.
Also because userbots aren't strictly supported (or allowed) they're not
gonna change it
