### ISSUE TITLE
Everything set-up and working properly... except the status message is not being displayed on Discord.

### ISSUE THREAD

**Issue by TheVasilisk** [DiNitride/Discord-Music-Status#46]
No clue what is happening, Snip is working properly, and the python shell is displaying
"[2018-01-07 05:07:37.545100] INFO: Discord Music: Set Discord status to Piano Man Billy Joel",
but my Discord status is not actually changing.

**Comment by TheVasilisk** [comment]
Nevermind, I didn't read the Readme properly... Sorry.

**Comment by miawgogo** [comment]
If you want to test without asking other people on the server your in you can look on the mobile app, it doesnt refresh instantly but allows you to check
