### ISSUE TITLE
Force Discord Music Status over games.

### ISSUE THREAD

**Issue by Nethful** [DiNitride/Discord-Music-Status#48]
Is there a way to make it show what I'm listening to rather than the game I'm playing?

**Comment by MrHugelberg** [comment]
Hmm why you don't just deactivate the game activiy settings in your discord client then?
So discord won't even try to show what game you are currently playing.

i mean, isn't that exactly what you are looking for?

If so -> Settings --> "App Settings" --> Game Activity

**Comment by DiNitride** [comment]
Yeah, disable it picking games up off your PC, otherwise there's no way to stop Dsicord overriding it
