### ISSUE TITLE
Can't get the localStorage.token

### ISSUE THREAD

**Issue by jia-se** [DiNitride/Discord-Music-Status#5]
![image](https://user-images.githubusercontent.com/29690969/27766505-85a57f6a-5ea8-11e7-85e2-8676c653ad8c.png)
The console isn't recognizing the command.

**Comment by DiNitride** [comment]
They changed how it works, I haven't updated instructions, contact me on Discord and I will sort it out for you

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SuGolYolLom** [comment]
1. While on the Discord Desktop app press `ctrl + shift + i`
2. Switch to `Application` tab
3. Go to `Storage` > `Local Storage` 
4. Find `token`
5. Copy the token inside the quotation marks

**Comment by DiNitride** [comment]
@InAGiiZ thanks, I forgot

**Comment by NullDev** [comment]
Is there any update on this one? 
I wasn't able to find out what method they use to read and write localStorage yet. 

Don't get me wrong: I know how to obtain the token manually. (Dev Tools -> Application -> Storage -> Token) but I want to automate that process for a SelfBot I'm currently working on. 

Is there a way to obtain it directly? I tried to experiment a bit with `localStorage` as well as `Storage.getItem()` but no luck so far.

**Comment by DiNitride** [comment]
The method may have changed, I don't have access to Discord currently but
I'll check if they've changed the location of the token
