### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by c-stella** [DiNitride/Discord-Music-Status#53]
Requirements correctly loaded, I don't know what the problem is.
note that I have tried with Python 3.6.5, 3.6.4 and 3.6.0. (now i'm on 3.6.5)
I have tried reinstalling anaconda but it won't solve the problem. any thoughts?
ScreenShot: https://i.gyazo.com/6c4eb87427e7c32d84914ddb27e3e6ff.png

**Comment by DiNitride** [comment]
This program is untested with anaconda, however you are having the same issue as #40 so it seems that there is some sort of incompatibility.

**Comment by c-stella** [comment]
Thanks for reply!
so I tried installing normal python 3.6, and it went well.
by the way are there plans to test with anaconda?
because there are people who want(prefer) to use Anaconda.(including me.)
anyway, thank you for making this!

**Comment by DiNitride** [comment]
To be perfectly honest with you, I have no idea what Anaconda is because
I've never used it. I'm busy with exams at the moment but if I remember
over summer when I have time I'll have a look, no promises though.
