### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by agiganticmidget** [DiNitride/Discord-Music-Status#54]
Not sure what I am doing wrong here.
![syntax error](https://user-images.githubusercontent.com/39574808/40459210-1c847b36-5ece-11e8-8f1f-b8068667a468.png)

**Comment by DiNitride** [comment]
What version of Python are you on

**Comment by agiganticmidget** [comment]
I am using Python 3.7

**Comment by DiNitride** [comment]
Hm, strange. Let me check that there hasn't been a library update

**Comment by DiNitride** [comment]
Sorry for the delay, I have exams currently. I have set up a fresh environment using Python 3.6.5 and have no issues, so it is most likely an issue with Python 3.7. Until my exams are done I have no time to look into the issue on 3.7, so I'd advise running a Python 3.6 venv for the script.
