### ISSUE TITLE
"No such file or directory" problem

### ISSUE THREAD

**Issue by pufek13** [DiNitride/Discord-Music-Status#58]
I use Python 3.6.0, token and Snip.txt location is correct (lost count on checks.) All the folders are not in desktop folder. Snip runs in the background, while listening to Winamp. Still getting the error, tho.

![untitled](https://user-images.githubusercontent.com/36480673/45779732-18917880-bc5c-11e8-8296-7ce4d31eda1d.png)

Any suggestions?

**Comment by DiNitride** [comment]
Can I see your config file please
