### ISSUE TITLE
Error message on run

### ISSUE THREAD

**Issue by cub149** [DiNitride/Discord-Music-Status#7]
When I try to run the program, it logs in fine and seems to get close to finishing when it shows me this:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
I'm not sure what that means since im kind of a noob to this stuff, but this program looks really cool so I hope you can help ><

**Comment by DiNitride** [comment]
Can you specify when this error happens?

The program should load up, log in, and then proceed to update your status on Discord and stay open, continually updating it.

**Comment by DiNitride** [comment]
Alright @cub149 I've just pushed a new version, please download that and try and tell me how you get on
