### ISSUE TITLE
Getting error, have configured correctly?

### ISSUE THREAD

**Issue by ghost** [DiNitride/Discord-Music-Status#8]
![error](https://user-images.githubusercontent.com/31202059/29506954-a3db7e80-8680-11e7-90c9-bbb6401a2534.PNG)

I keep getting this error, I'm certain I've configured it correctly. What's going on?

**Comment by DiNitride** [comment]
Show me your config

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
[Config]
token = aaaaaaaaaaaaaaaaaaaaaaaa.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaa
snip = C:\Users\Hussain\Desktop\Discord Music Status\Snip\Snip.exe

(Replaced token with a's)

**Comment by DiNitride** [comment]
Please refer to the example config, your snip configuration is pointing to the incorrect file

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Cheers, that fixed it.
